// <auto-generated />
namespace chat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class sql004 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sql004));
        
        string IMigrationMetadata.Id
        {
            get { return "201405271941274_sql004"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
